### ISSUE TITLE
The background color of the bottom navigation bar is not visible.

### ISSUE THREAD

**Issue by toFrankie** [RSSNext/Folo#3916]
### Platform

Mobile - iOS

### Describe the bug

When the application is cold started, the background color of the bottom navigation bar on the home page is not visible.

Screenshot as follows:

![Image](https://github.com/user-attachments/assets/f4360c54-3c2b-42df-806c-db1dca0e4da5)

### Relevant Information

None

### Reproduction Video

None

### Environment

- iPhone 15 Pro Max
- iOS 18.5
- Folo 0.2.1(112)

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [x] This issue is valid

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
This problem has been fixed in the latest version

**Comment by tofrankie** [comment]
Updated to the latest version 0.2.3, the problem still exists.

<img width="1290" height="2796" alt="Image" src="https://github.com/user-attachments/assets/20cad60d-9083-4371-825d-1269009cdbb7" />
